#! /bin/bash

# Flag to be set to (yes / no), whether there is software to be installed on RPis in Lab, or not

NEW_SW=no

if [[ $NEW_SW == "yes" ]];
then
    echo "There is new Software for installation."
    read -p "Do you want to install it now ? (y/n) " op
    if [[ $op == "y" ]];
    then
        
        echo

        echo 'updating ... '
        sudo apt-get update

        echo
        echo 'installing kolourpaint ...'
        sudo apt-get -y install kolourpaint
    else
        exit
    fi        
else
    echo "There is no new software to install"
fi
