#! /bin/sh

# Flag to be set to (yes / no), whether there is software to be installed on RPis in Lab, or not

NEW_SW=No

if [[ $NEW_SW == "yes" ]];
then
    echo

    echo 'updating ... '
    sudo apt-get update

    echo
    echo 'installing shotwell ...'
    sudo apt-get -y install shotwell
else
    echo "There is no new software to install"
fi
